# Generated by Django 4.2.11 on 2024-07-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_usernotification_subscription_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='encoded_user_auth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='encoded_user_public_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='endpoint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
