# Generated by Django 4.2.11 on 2024-08-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_usernotification_encoded_user_auth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='unread_notifications_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
